export const roles = [
    "frontend-development",
    "backend-development",
    "web-development",
    "full-stack-development",
    "software-development",
    "security-engineering",
    "api-development",
    "data-analysis",
    "data-engineering",
    "data-science",
    "database-administration",
    "devops",
    "machine-learning-engineering",
    "mobile-app-development",
];